### ISSUE TITLE
hur man visar identitet

### ISSUE THREAD

**Issue by shyricaus** [jonassvensson4/jsfour-legitimation#1]
hur man visar identitet eftersom det inte finns någon nyckel att trycka på

**Comment by jnsvns** [comment]
There's a menu at the bottom. Please look at that and you'll see how it works

**Comment by shyricaus** [comment]
Thanks, I've already been able to solve it, so I'm having another problem. with the date being appearing (-) where it was to appear numbers

![image](https://user-images.githubusercontent.com/28937245/46920292-721e6600-cfc2-11e8-8bc8-d73a1b472988.png)
